version: '3'
# This is for local dev deployments. It will not grab the latest docker 
# image for the django app from the docker repo. It will build and deploy the local
# changes
# DO NOT DELETE
services:
  testing:
    build:
        context: .
        dockerfile: Dockerfile
